Use flock instead of old plock

diff --git a/rdp b/rdp
--- a/rdp
+++ b/rdp
@@ -4,14 +4,14 @@
 
 PROGRAM_NAME=$(basename "$0")
 CONF_DIR=~/".rdesktop"
-LOCK_FILE="${CONF_DIR}.lock"
+LOCK_FILE="${CONF_DIR}/.lock"
 MENU_DIR_LOCAL=~/".local/share/applications"
 MENU_DIR_CONFIG=~/".config/menus"
 DESKTOP_DIR=~/".local/share/desktop-directories"
 SECURE_DIR=~/"secure"
 MENU_FILENAME="remote-access.menu"
 DIR_FILENAME="remote-access.directory"
-ERROR_FILE="${CONF_DIR}-error"
+ERROR_FILE="${CONF_DIR}/error"
 
 if [ -z "$GIO_LAUNCHED_DESKTOP_FILE_PID" ]
 then
@@ -20,10 +20,13 @@ else
   INTERACTIVE=0
 fi
 
-if ! checkDependencies $PROGRAM_NAME ssh sshpass ssh-copy-id xmlstarlet nmap arp rdesktop gxmessage plock vncviewer terminal:mate-terminal,gnome-terminal xrandr xwininfo notify-send crudini nmblookup
+if ! checkDependencies $PROGRAM_NAME ssh sshpass ssh-copy-id xmlstarlet nmap arp rdesktop gxmessage flock vncviewer terminal:mate-terminal,gnome-terminal xrandr xwininfo notify-send crudini nmblookup
 then
   exit -1
 fi
+
+# Creates the lock file
+: >> "${LOCK_FILE}"
 
 PANELS="$(LC_ALL=C \
           ${XWININFO} -root -tree \
@@ -241,16 +244,17 @@ regenerate()
 {
   echo "Create access description for : "
 
-  $PLOCK -l "${LOCK_FILE}" > /dev/null 2>&1
+  {
+    $FLOCK $fd
 
-  mkdir -p "${MENU_DIR_CONFIG}" "${MENU_DIR_LOCAL}" "${DESKTOP_DIR}" "${SECURE_DIR}" "${CONF_DIR}"
-  chmod 700 "${CONF_DIR}"
+    mkdir -p "${MENU_DIR_CONFIG}" "${MENU_DIR_LOCAL}" "${DESKTOP_DIR}" "${SECURE_DIR}" "${CONF_DIR}"
+    chmod 700 "${CONF_DIR}"
 
-  OLD_LIST=$(grep -wrl "Exec=$RDP" "${MENU_DIR_LOCAL}/${PROGRAM_NAME}@"*.desktop 2>/dev/null)
+    OLD_LIST=$(grep -wrl "Exec=$RDP" "${MENU_DIR_LOCAL}/${PROGRAM_NAME}@"*.desktop 2>/dev/null)
 
-  local MENUS=$(ls -1 ${CONF_DIR}/*.conf | while read f; do echo "$(basename "$f" .conf)"; done | sort -u)
+    local MENUS=$(ls -1 ${CONF_DIR}/*.conf | while read f; do echo "$(basename "$f" .conf)"; done | sort -u)
 
-  cat > "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" 2>/dev/null <<!
+    cat > "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" 2>/dev/null <<!
 <!DOCTYPE Menu
   PUBLIC '-//freedesktop//DTD Menu 1.0//EN'
   'http://standards.freedesktop.org/menu-spec/menu-1.0.dtd'>
@@ -269,7 +273,7 @@ $(echo "$MENUS" | sed "s;\(.*\);        <Menuname>\1</Menuname>;g")
 </Menu>
 !
 
-  cat > "${DESKTOP_DIR}/${DIR_FILENAME}" <<!
+    cat > "${DESKTOP_DIR}/${DIR_FILENAME}" <<!
 [Desktop Entry]
 Comment=Remote Access
 Comment[it_CH]=Accesso Remoto
@@ -286,13 +290,13 @@ Version=1.0
 NoDisplay=false
 !
 
-  for MENU in $MENUS
-    do
-      FILENAME="${DESKTOP_DIR}/${MENU}.directory"
+    for MENU in $MENUS
+      do
+        FILENAME="${DESKTOP_DIR}/${MENU}.directory"
 
-      if [ ! -z "${MENU}" -a ! -f "${FILENAME}" ]
-      then
-        cat > "${FILENAME}" <<!
+        if [ ! -z "${MENU}" -a ! -f "${FILENAME}" ]
+        then
+          cat > "${FILENAME}" <<!
 [Desktop Entry]
 Encoding=UTF-8
 Icon=folder
@@ -307,56 +311,56 @@ Comment[it_CH]=${MENU}
 Comment[fr_CH]=${MENU}
 Comment=${MENU}
 !
-      fi
-    done
+        fi
+      done
 
-  LIST=$(for MENU in $MENUS
-         do
-           $CRUDINI --get "${CONF_DIR}/${MENU}.conf" \
-           | sort -u \
-           | while read ALIAS
-             do
-               PROTOCOL="$($CRUDINI --get "${CONF_DIR}/${MENU}.conf" "$ALIAS" protocol 2>/dev/null)"
-               WIDE="$($CRUDINI --get "${CONF_DIR}/${MENU}.conf" "$ALIAS" wide 2>/dev/null)"
+    LIST=$(for MENU in $MENUS
+           do
+             $CRUDINI --get "${CONF_DIR}/${MENU}.conf" \
+             | sort -u \
+             | while read ALIAS
+               do
+                 PROTOCOL="$($CRUDINI --get "${CONF_DIR}/${MENU}.conf" "$ALIAS" protocol 2>/dev/null)"
+                 WIDE="$($CRUDINI --get "${CONF_DIR}/${MENU}.conf" "$ALIAS" wide 2>/dev/null)"
 
-               if [ ! -z "$ALIAS" ]
-               then
-                 if [ "$PROTOCOL" == "RDP" ]
+                 if [ ! -z "$ALIAS" ]
                  then
-                   ICON="application-x-remote-connection"
-                 elif [ "$PROTOCOL" == "VNC" ]
-                 then
-                   ICON="application-x-vnc"
-                 elif [ "$PROTOCOL" == "SSH" ]
-                 then
-                   ICON="utilities-terminal"
-                 fi
-
-                 NAME[0]="${ALIAS}"
-                 OPT[0]="${ALIAS}"
-
-                 if [ "$WIDE" == "true" ]
-                 then
-                   NAME[1]="${ALIAS}(wide)"
-                   OPT[1]="-w ${ALIAS}"
-                 else
-                   NAME[1]=""
-                   OPT[1]=""
-                 fi
-
-                 for i in 0 1
-                 do
-                   if [ -z "${NAME[i]}" ]
+                   if [ "$PROTOCOL" == "RDP" ]
                    then
-                     break
+                     ICON="application-x-remote-connection"
+                   elif [ "$PROTOCOL" == "VNC" ]
+                   then
+                     ICON="application-x-vnc"
+                   elif [ "$PROTOCOL" == "SSH" ]
+                   then
+                     ICON="utilities-terminal"
                    fi
 
-                   FILENAME="${MENU_DIR_LOCAL}/${PROGRAM_NAME}@${MENU}#${NAME[i]}.desktop"
-                   echo "${FILENAME}"
-                   sed -i "s;\(        <!--Entry:${MENU}-->\);        <Include><Filename>$(basename ${FILENAME})</Filename></Include>\n\1;g;
-                           s;\(            <!--Layout:${MENU}-->\);            <Filename>$(basename ${FILENAME})</Filename>\n\1;g;" \
-                          "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" >&2
-                   cat > "${FILENAME}" <<!
+                   NAME[0]="${ALIAS}"
+                   OPT[0]="${ALIAS}"
+
+                   if [ "$WIDE" == "true" ]
+                   then
+                     NAME[1]="${ALIAS}(wide)"
+                     OPT[1]="-w ${ALIAS}"
+                   else
+                     NAME[1]=""
+                     OPT[1]=""
+                   fi
+
+                   for i in 0 1
+                   do
+                     if [ -z "${NAME[i]}" ]
+                     then
+                       break
+                     fi
+
+                     FILENAME="${MENU_DIR_LOCAL}/${PROGRAM_NAME}@${MENU}#${NAME[i]}.desktop"
+                     echo "${FILENAME}"
+                     sed -i "s;\(        <!--Entry:${MENU}-->\);        <Include><Filename>$(basename ${FILENAME})</Filename></Include>\n\1;g;
+                             s;\(            <!--Layout:${MENU}-->\);            <Filename>$(basename ${FILENAME})</Filename>\n\1;g;" \
+                            "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" >&2
+                     cat > "${FILENAME}" <<!
 [Desktop Entry]
 Categories=RemoteAccess;
 Comment=
@@ -374,16 +378,16 @@ Type=Application
 X-KDE-SubstituteUID=false
 X-KDE-Username=
 !
-                 done
-               fi
-             done
+                   done
+                 fi
+               done
 
-           FILENAME="${MENU_DIR_LOCAL}/${PROGRAM_NAME}@${MENU}#ALL.desktop"
-           echo "${FILENAME}"
-           sed -i "s;\(        <!--Entry:${MENU}-->\);        <Include><Filename>$(basename ${FILENAME})</Filename></Include>\n\1;g;
-                   s;\(            <!--Layout:${MENU}-->\);            <Filename>$(basename ${FILENAME})</Filename>\n\1;g;" \
-                  "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" >&2
-           cat > "${FILENAME}" <<!
+             FILENAME="${MENU_DIR_LOCAL}/${PROGRAM_NAME}@${MENU}#ALL.desktop"
+             echo "${FILENAME}"
+             sed -i "s;\(        <!--Entry:${MENU}-->\);        <Include><Filename>$(basename ${FILENAME})</Filename></Include>\n\1;g;
+                     s;\(            <!--Layout:${MENU}-->\);            <Filename>$(basename ${FILENAME})</Filename>\n\1;g;" \
+                    "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" >&2
+             cat > "${FILENAME}" <<!
 [Desktop Entry]
 Categories=RemoteAccess;
 Comment=
@@ -401,39 +405,38 @@ Type=Application
 X-KDE-SubstituteUID=false
 X-KDE-Username=
 !
-         done)
+           done)
 
-  echo "$LIST
+    echo "$LIST
 $OLD_LIST
 $OLD_LIST" \
-  | sort \
-  | uniq -c \
-  | while read op file
-    do
-      if [ "$f" != "$file" ]
-      then
-        case "$op" in
-          1) echo "Created  $(basename $file)"
-             ;;
-          2) echo "Deleted  $(basename $file)"
-             rm -f "$file"
-             ;;
-          3) echo "Replaced $(basename $file)"
-             ;;
-          *) echo "$file (INTERNAL ERROR)"
-             ;;
-        esac
-      fi
+    | sort \
+    | uniq -c \
+    | while read op file
+      do
+        if [ "$f" != "$file" ]
+        then
+          case "$op" in
+            1) echo "Created  $(basename $file)"
+               ;;
+            2) echo "Deleted  $(basename $file)"
+               rm -f "$file"
+               ;;
+            3) echo "Replaced $(basename $file)"
+               ;;
+            *) echo "$file (INTERNAL ERROR)"
+               ;;
+          esac
+        fi
 
-      f="$file"
-    done \
-  | sort -k2
+        f="$file"
+      done \
+    | sort -k2
 
-  cat "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" > "${MENU_DIR_CONFIG}/${MENU_FILENAME}" 2>/dev/null
+    cat "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$" > "${MENU_DIR_CONFIG}/${MENU_FILENAME}" 2>/dev/null
 
-  rm -f "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$"
-
-  $PLOCK -u "${LOCK_FILE}" > /dev/null 2>&1
+    rm -f "${MENU_DIR_CONFIG}/${MENU_FILENAME}.$$"
+  } {fd}<"${LOCK_FILE}"
 }
 
 checkMac()
@@ -532,11 +535,12 @@ Please specify it manually!"
         [ "$INTERACTIVE" -eq 0 ] && $NOTIFYSEND --urgency=low --icon=error --app-name=rdp "$MSG"
         NEW_ADDR=$ADDRESS
       else
-        $PLOCK -l "${LOCK_FILE}" > /dev/null 2>&1
-        echo "Update configuration file ${CONF_DIR}/${MENU}.conf" >&2
-        $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" address "$NEW_ADDR"
-        $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" mac "$MAC"
-        $PLOCK -u "${LOCK_FILE}" > /dev/null 2>&1
+        {
+          $FLOCK $fd
+          echo "Update configuration file ${CONF_DIR}/${MENU}.conf" >&2
+          $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" address "$NEW_ADDR"
+          $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" mac "$MAC"
+        } {fd}<"${LOCK_FILE}"
       fi
     fi
 
@@ -585,12 +589,12 @@ getMac()
     echo "Unable to find MAC address" >&2
   else
     echo "Found MAC address '${MAC}'" >&2
-
-    $PLOCK -l "${LOCK_FILE}" > /dev/null 2>&1
-    echo "Update configuration file ${CONF_DIR}/${MENU}.conf" >&2
-    $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" address "$ADDRESS"
-    $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" mac "$MAC"
-    $PLOCK -u "${LOCK_FILE}" > /dev/null 2>&1
+    {
+      $FLOCK $fd
+      echo "Update configuration file ${CONF_DIR}/${MENU}.conf" >&2
+      $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" address "$ADDRESS"
+      $CRUDINI --set "${CONF_DIR}/${MENU}.conf" "$ALIAS" mac "$MAC"
+    } {fd}<"${LOCK_FILE}"
   fi
 
   echo "$MAC"
